export const RegexConstants = {
  ANY_SINGLE_DIGIT_ZERO_THROUGH_NINE: /[0-9]/,
  EXPONENTIAL_FORMAT_ANY_COEFFICIENT_ANY_EXPONENT: /[0-9]+ e [0-9]+/,
  EXPONENTIAL_FORMAT_WITHOUT_COEFFICIENT: /0 e [1-9]/,
  EXPONENTIAL_FORMAT_WITHOUT_EXPONENT: /[1-9] e 0/,
  EXPONENTIAL_FORMAT_NEGATIVE_EXPONENT: /[0-9] e -[1-9]/,
  EXPONENTIAL_FORMAT_NATURAL_COEFFICIENT_WITH_ANY_EXPONENT: /[1-9]+ e [0-9]+/,


};
