export const RegexConstants = {
  ANY_OPERATOR: /[÷*\-+]/,
  ANY_SPECIFIED_KEY: /(π|e|Rand)/,
  ANY_SINGLE_DIGIT_ZERO_THROUGH_NINE: /[0-9]/,
  CHECK_FOR_MULTIPLICATION_DIVISION_EQUATION_WITH_PRECEDING_NEGATIVE:
    /[÷+*-]-[0-9.]+[÷*]-?[0-9.]+/,
  DECIMAL_NUMBER_15_DIGITS_NOT_NOTATED: /\.[0-9]+[^e+]{15,}/,
  EXPONENTIAL_FORMAT_ANY_COEFFICIENT_ANY_EXPONENT: /-?[0-9.]+ e -?[0-9]+/,
  EXPONENTIAL_FORMAT_NATURAL_COEFFICIENT_WITH_ANY_EXPONENT:
    /-?[1-9]+ e -?[0-9]+/,
  EXPONENTIAL_FORMAT_NEGATIVE_EXPONENT: /-?[0-9]+ e -[1-9]+/,
  EXPONENTIAL_FORMAT_NEGATIVE_COEFFICIENT_NEGATIVE_EXPONENT: /-[0-9]+\s?e\s?-[1-9]+/,
  EXPONENTIAL_FORMAT_WITHOUT_COEFFICIENT: /^0\s?e\s?-?[0-9]+$/,
  EXPONENTIAL_FORMAT_WITHOUT_EXPONENT: /-?[0-9]+ e 0/,
  EXPONENTIAL_NOTATED_MORE_THAN_14_PLACES: /[0-9]+\.[0-9]{15,}e[1-9]+/,
  EXPONENTIAL_NOTATION_FORMAT_EMPTY: /^0\s?e\s?0$/,
  FLOAT_MORE_THAN_15_PLACES: /[0-9]+\.[0-9]{16,}/,
  MOST_INSIDE_PARENTHESIS: /\([0-9÷*\-+.][^)]\)/,
  MULTIPLICATION_DIVISION_EQUATION_WITH_PRECEDING_NEGATIVE:
    /-[0-9.]+[÷*]-?[0-9.]+/,
  MULTIPLICATION_DIVISION_EQUATION_WITHOUT_PRECEDING_NEGATIVE:
    /[0-9.]+[÷*]-?[0-9.]+/,
  NEGATIVE_NOTATED_NUMBER_7_15: /\s?e\s?-(7|8|9|10|11|14|15)$/,
  NOTATED_NUMBER_WITH_LOTS_OF_ZEROS_AFTER: /1\.[0]{10,}e[0-9]+/,
  NUMBER_OUTSIDE_OF_PARENTHESIS_WITH_NO_PRECEDING_OPERATOR:
    /^[0-9]+[÷*\-+]\([0-9÷*\-+]+\)[0-9]+/,
  NUMBERS_AND_OPERATOR_BEFORE_LEFT_PARENTHESIS: /^[0-9][÷*\-+]\(/,
  STRING_STARTING_WITH_EQUATION_WITH_ANY_OPERATOR: /^(-?[0-9]+[+\-÷*]-?[0-9]+)/,
  STRING_WITH_ADDITION_SUBTRACTION_OPERATORS: /[0-9]+[+-]+[0-9]+/,
  STRING_WITH_MULTIPLICATION_DIVISION_OPERATORS: /[0-9]+(÷-|÷|\*-|\*)+[0-9]+/,
  STRING_WITHOUT_ANY_OPERATORS: /^[^+\-÷*]+$/,
  WHOLE_NUMBER_MORE_THAN_15_PLACES: /^[0-9]{16,}$/,
  EXPONENTIAL_FORMAT_NATURAL_EXPONENT: /^-?[0-9] e [0-9]/,
};
