export const ShortcutKeyConstants = {
  ADDITION_SYMBOL: ["+"],
  BACKSPACE: ["backspace"],
  CARET_SYMBOL: ["^"],
  CLEAR: ["c"],
  CLEAR_ALL: ["option", "escape"],
  CLEAR_ESC: ["escape"],
  COMMA: [","],
  CONTROL_ONE: ["control", "1"],
  CONTROL_TWO: ["control", "2"],
  CONTROL_THREE: ["control", "3"],
  DECIMAL_POINT: ["."],
  DIVISION_SYMBOL: ["/"],
  EE: ["E"],
  EIGHT: ["8"],
  ENTER: ["Enter"],
  EQUALS: ["="],
  EXCLAMATION_POINT: ["!"],
  EXPONENT: ["^"],
  FIVE: ["5"],
  FOUR: ["4"],
  LEFT_PARENTHESIS: ["("],
  MULTIPLICATION_SYMBOL: ["*"],
  NATURAL_LOG: ["e"],
  NEGATE_VALUE: ["Option", "-"],
  NINE: ["9"],
  ONE: ["1"],
  PERCENTAGE_SYMBOL: ["%"],
  PI: ["p"],
  RIGHT_PARENTHESIS: [")"],
  SEVEN: ["7"],
  SHIFT: ["Shift"],
  SHORTENED_CONTROL_ONE: "cntl+1",
  SHORTENED_CONTROL_TWO: "cntl+2",
  SHORTENED_CONTROL_THREE: "cntl+3",
  SHORTENED_TOGGLE_PAPER_TAPE: "cntl+t",
  TOGGLE_PAPER_TAPE: ["control", "t"],
  SIX: ["6"],
  SUBTRACTION_SYMBOL: ["-"],
  THREE: ["3"],
  TWO: ["2"],
  ZERO: ["0"],
};
